### ISSUE TITLE
a区价格显示为0

### ISSUE THREAD

**Issue by CabbCat** [NoErla/steam_checker#4]
从老版本更新上来的，a区价格无论什么游戏都显示为 阿区价格(元):0.0
已写入api和固定汇率...

**Comment by CabbCat** [comment]
发现不是每个游戏都显示0.0
![_ X(LTE~ CG0MLOQ))76P8Q](https://user-images.githubusercontent.com/37258131/151746835-b957d577-c04f-444c-b466-eb857033e258.jpg)

**Comment by NoErla** [comment]
谢谢，已确认该BUG。
原因应该是阿根廷比索这个货币的表示方式比较奇葩。本该是小数点的位置用逗号来表示，超过1000比索的又会用小数点来分割。具体来说就是GTOF这款游戏用阿根廷比索来表示价格的话：ARS$ 1.032,00
超过1000比索的游戏会让我写的货币解析器出现异常，最后显示为0元。
预计这两天就修复该问题。

**Comment by CabbCat** [comment]
> 

好的，谢谢大佬，新年快乐）

**Comment by NoErla** [comment]
新年快乐:collision::collision::collision:

**Comment by CabbCat** [comment]
不好意思打扰大佬了，问一下新版本大概什么时候release......
